apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: odoo-db
  labels:
    app: odoo-shop
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: odoo-shop
        tier: backend
    spec:
      containers:
      - image: postgres:9.4
        name: odoo-db
        env:
        - name: POSTGRES_DB
          value: db
        - name: POSTGRES_USER
          value: odoo
        - name: POSTGRES_PASSWORD
          value: password
        ports:
        - containerPort: 5432
          name: odoo-db
