apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: odoo-shop
  labels:
    app: odoo-shop
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: odoo-shop
        tier: frontend
    spec:
      containers:
        - image: odoo:10
          name: odoo
          env:
          - name: HOST
            value: odoo-db
          - name: USER
            value: odoo
          - name: PASSWORD
            value: password
          ports:
            - containerPort: 8069
              name: odoo
