---
apiVersion: v1
kind: Service
metadata:
  name: odoo-db
  namespace: odoo-shop
spec:
  ports:
    - name: odoo-db
      protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    name: odoo-db
